// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class User {
// /*
// {
//   "address": "6th of october",
//   "email": "asd@asd.com",
//   "name": "asd",
//   "phone": "12345678"
// }
// */

//   String? uid;
//   String? email;
//   String? name;

//   User({
//     this.uid,
//     this.email,
//     this.name,
//   });
//   User.fromJson(Map<String, dynamic> json) {
//     uid = json['uid']?.toString();
//     email = json['email']?.toString();
//     name = json['name']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['uid'] = uid;
//     data['email'] = email;
//     data['name'] = name;
//     return data;
//   }

//   @override
//   String toString() => '$uid $email $name';
// }
