///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Categories {
/*
{
  "id": 1,
  "title": "Updated Category",
  "image": "https://via.placeholder.com/640x480.png/0000ee?text=voluptatum.jpg",
  "created_at": "2024-03-02T12:24:51.000000Z",
  "updated_at": "2024-03-02T13:59:14.000000Z"
} 
*/

  int? id;
  String? title;
  String? image;
  String? createdAt;
  String? updatedAt;

  Categories({
    this.id,
    this.title,
    this.image,
    this.createdAt,
    this.updatedAt,
  });
  Categories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    image = json['image']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['image'] = image;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
