///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Product {
/*
{
  "id": 1,
  "name": "Product 1 in Category 1",
  "image": "https://via.placeholder.com/640x480.png/00ffdd?text=numquam",
  "description": "Description of Product 1 in Category 1",
  "price": "58.00",
  "category_id": 1,
  "created_at": "2024-03-16T14:09:26.000000Z",
  "updated_at": "2024-03-16T14:09:26.000000Z"
} 
*/

  int? id;
  String? name;
  String? image;
  String? description;
  String? price;
  int? categoryId;
  String? createdAt;
  String? updatedAt;

  Product({
    this.id,
    this.name,
    this.image,
    this.description,
    this.price,
    this.categoryId,
    this.createdAt,
    this.updatedAt,
  });
  Product.fromJson(Map<String, dynamic> json) {
    id = int.tryParse(json['id']?.toString() ?? '');
    name = json['name']?.toString();
    image = json['image']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toString();
    categoryId = int.tryParse(json['category_id']?.toString() ?? '');
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['description'] = description;
    data['price'] = price;
    data['category_id'] = categoryId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
